services:
  - type: web
    name: golfwang-chatbot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python download_model.py
    startCommand: gunicorn run:app

